name: quality gateway implementation

on:
  push:
    branches:
      - main

jobs:
  run-python-code:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v7
      - name: install require package
        run: pip install -r requirements.txt
      - name: run test 
        run: pytest -- cov=calculator --cov-report=term


